RAShop.CustomerSite/Pages/Cart/ShoppingCart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RAShop.CustomerSite.Interfaces;
using RAShop.CustomerSite.Models;
using RAShop.Shared.DTO;
namespace RAShop.CustomerSite.Pages.Home
{
    public class ShoppingCartModel : PageModel
    {
        private readonly ICart _cartService;
        [BindProperty]
        public List<CartDTO> cart {get; set;} = new List<CartDTO>();
        public ShoppingCartModel(ICart cartService)
        {
            _cartService = cartService;
        }
        public ActionResult OnGetAsync()
        {
            cart = _cartService.GetCart();
            return Page();
        }
        public IActionResult OnGetAddToCart(int id)
        {
            _cartService.AddToCart(id);
            CountCart.countItem = _cartService.CountItem(); 
            return RedirectToPage("ShoppingCart");
        }
           public IActionResult OnGetRemoveItem(int id)
        {
            _cartService.RemoveItem(id);
            CountCart.countItem = _cartService.CountItem(); 
            return RedirectToPage("ShoppingCart");
        }
    }
}

RAShop.CustomerSite/Pages/Cart/ShoppingCart.cshtml
@page 
@using RAShop.CustomerSite.Pages.Home
@model ShoppingCartModel
@{
  double total = 0;
}
<div class="container px-3 my-5 clearfix">
  <!-- Shopping cart table -->
  <div class="card">
    <div class="card-header">
      <h2>Giỏ hàng</h2>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered m-0">
          <thead>
            <tr>
              <!-- Set columns width -->
              <th class="text-center py-3 px-4" style="min-width: 400px;">Sản phẩm</th>
              <th class="text-right py-3 px-4" style="width: 100px;">Giá</th>
              <th class="text-center py-3 px-4" style="width: 120px;">Số lượng</th>
              <th class="text-right py-3 px-4" style="width: 100px;">Tổng tiền</th>
              <th class="text-center align-middle py-3 px-0" style="width: 40px;"><a href="#"
                  class="shop-tooltip float-none text-light" title="" data-original-title="Clear cart"><i
                    class="ino ion-md-trash"></i></a></th>
            </tr>
          </thead>
          <tbody>
            @foreach (var item in Model.cart)
            {
              total = total + @item.Total;
              <tr>
                <td class="p-4">
                  <div class="media align-items-center">
                    <img src="@item.Product.MainImg" class="d-inline-block ui-w-40 ui-bordered mr-4" alt="@item.Product.ProductName">
                      <a asp-page="/Product/GetProductDetail" asp-route-id="@item.Product.ProductId" class="d-inline-block text-dark fs-5">@item.Product.ProductName</a>
                    <div class="media-body">
                      <small>
                        <span class="text-muted">Xuất xứ: @item.Product.Origin</span>
                        <span class="text-muted ms-3">Đơn vị: @item.Product.Unit</span> 
                      </small>
                    </div>
                  </div>
                </td>
                <td class="text-right font-weight-semibold align-middle p-4">@string.Format("{0:#,##0.##}₫", @item.Product.Price)</td>
                <td class="align-middle p-4"><input type="text" class="form-control text-center" value="@item.Quantity"></td>
                <td class="text-right font-weight-semibold align-middle p-4">@string.Format("{0:#,##0.##}₫", @item.Total)</td>
                <td class="text-center align-middle px-0"><a asp-page="ShoppingCart" asp-page-handler="RemoveItem" asp-route-id="@item.Product.ProductId" class="shop-tooltip close float-none text-danger"
                  title="" data-original-title="Remove">X</a></td>
              </tr>
            }

          </tbody>
        </table>
      </div>
      <!-- / Shopping cart table -->

      <div class="d-flex flex-wrap justify-content-between align-items-center pb-4">
        <div class="d-flex">
          <div class="text-right mt-4 ">
            <label class="text-muted font-weight-normal m-0">Tổng tiền</label>
            <div class="text-large"><strong>@string.Format("{0:#,##0.##}₫", @total)</strong></div>
          </div>
        </div>
      </div>

      <div class="float-right">
        <button type="button" class="btn btn-pay btn-danger mt-2" style="float:right ;">Thanh toán</button>
        <a asp-page="/Product/ProductIndex" type="button" class="btn btn-lg btn-default md-btn-flat mt-2 mr-3" style="float: left;">Trở lại</a>
      </div>

    </div>
  </div>
</div>