RAShop.CustomerSite/Pages/Cart/ShoppingCart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RAShop.CustomerSite.Interfaces;
using RAShop.CustomerSite.Models;
using RAShop.Shared.DTO;
namespace RAShop.CustomerSite.Pages.Home
{
    public class ShoppingCartModel : PageModel
    {
        private readonly ICart _cartService;
        [BindProperty]
        public List<CartDTO> cart {get; set;} = new List<CartDTO>();
        public ShoppingCartModel(ICart cartService)
        {
            _cartService = cartService;
        }
        public ActionResult OnGetAsync()
        {
            cart = _cartService.GetCart();
            return Page();
        }
        public IActionResult OnGetAddToCart(int id)
        {
            _cartService.AddToCart(id);
            CountCart.countItem = _cartService.CountItem(); 
            return RedirectToPage("ShoppingCart");
        }
           public IActionResult OnGetRemoveItem(int id)
        {
            _cartService.RemoveItem(id);
            CountCart.countItem = _cartService.CountItem(); 
            return RedirectToPage("ShoppingCart");
        }
    }
}

RAShop.CustomerSite/Pages/Product/GetProductByCateId.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RAShop.CustomerSite.Interfaces;

namespace RAShop.CustomerSite.Pages.Home
{
    public class GetProductByCateIdModel : PageModel
    {
        private readonly IProduct _productService;
        private readonly ICategory _categoryService;
        private readonly ISubCategory _subCategoryService;
        public GetProductByCateIdModel(IProduct productService, ICategory categoryService, ISubCategory subCategoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _subCategoryService = subCategoryService;
        }
        public async Task<IActionResult> OnGetAsync(int cateid, string sortOrder = "0", int pageCurrent = 1)
        {
            if (pageCurrent > 1)
                ViewData["page"] = pageCurrent;
            else
                ViewData["page"] = 1;
            if (sortOrder != "0")
                ViewData["sort"] = sortOrder;
            else
                ViewData["sort"] = "0";
            var data = await _productService.GetProductByCateId(cateid, sortOrder, pageCurrent);
                var temp = data.items.Find(x => x.CategoryId == cateid);
                // ViewData["nameCate"] = temp.CategoryName;
                ViewData["products"] = data.items;
                ViewData["totalPage"] = data.TotalPages;
                ViewData["cateId"] = cateid;
            return Page();
        }
    }
}

RAShop.CustomerSite/Pages/Product/GetProductBySubCateId.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RAShop.CustomerSite.Interfaces;
using RAShop.Shared.DTO;

namespace RAShop.CustomerSite.Pages.Home
{
    public class GetProductBySubCateIdModel : PageModel
    {
        private readonly IProduct _productService;
        private readonly ICategory _categoryService;
        private readonly ISubCategory _subCategoryService;
        public GetProductBySubCateIdModel(IProduct productService, ICategory categoryService, ISubCategory subCategoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _subCategoryService = subCategoryService;
        }
        public async Task<IActionResult> OnGetAsync(int cateid, string sortOrder = "0", int pageCurrent = 1)
        {
            if (pageCurrent > 1)
                ViewData["page"] = pageCurrent;
            else
                ViewData["page"] = 1;
            if (sortOrder != "0")
                ViewData["sort"] = sortOrder;
            else
                ViewData["sort"] = "0";
            var data = await _productService.GetProductBySubCateId(cateid, sortOrder, pageCurrent);
            var temp = data.items.Find(x => x.SubCategoryId == cateid);
            ViewData["nameSubCate"] = temp.SubCategoryName;
            ViewData["nameCate"] = temp.CategoryName;
            ViewData["totalPage"] = data.TotalPages;
            ViewData["cateId"] = cateid;
            ViewData["products"] = data.items;
            return Page();
        }
    }
}

RAShop.CustomerSite/Pages/Product/GetProductDetail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RAShop.CustomerSite.Interfaces;
using RAShop.Shared.DTO;
namespace RAShop.CustomerSite.Pages.Home
{
    public class GetProductDetail : PageModel
    {
        private readonly IProduct _productService;
        private readonly IRating _ratingService;
        [BindProperty]
        public ProductDTO product { get; set; } = new ProductDTO();
        public GetProductDetail(IProduct productService, IRating ratingService)
        {
            _productService = productService;
            _ratingService = ratingService;
        }
        public async Task<IActionResult> OnGetAsync(int id, string sortOrder = "0", int pageCurrent = 1)
        {
            product = await _productService.GetProductDetail(id);
            var ratingAvg = await _productService.GetRatingAVG(id);
            ViewData["listRatings"] = await _ratingService.GetProductRatings(id);
            if (ratingAvg != 0)
            {
                ViewData["ratingAvg"] = ratingAvg;
            }
            else
            {
                ViewData["ratingAvg"] = 0;
            }
            return Page();
        }
        public async Task<IActionResult> OnPostCreateRating()
        {
            AddRatingDTO newRating = new AddRatingDTO();
            newRating.ProductId = Convert.ToInt32(Request.Form["ProductId"]);
            newRating.Star = Convert.ToInt32(Request.Form["Star"]);
            newRating.Comment = Request.Form["Comment"];
            await _productService.CreateRating(newRating);
            return RedirectToPage(new {id = newRating.ProductId});
        }
    }
}

RAShop.CustomerSite/Pages/Product/ProductIndex.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RAShop.CustomerSite.Interfaces;

namespace RAShop.CustomerSite.Pages.Home
{
    public class ProductIndexModel: PageModel
    {
        private readonly IProduct _productService;
        private readonly ICategory _categoryService;
        private readonly ISubCategory _subCategoryService;
        public ProductIndexModel(IProduct productService, ICategory categoryService, ISubCategory subCategoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _subCategoryService = subCategoryService;
        }
     public async Task<IActionResult> OnGetAsync(string sortOrder = "0", int pageCurrent = 1)
        {
               if (pageCurrent > 1)
                ViewData["page"] = pageCurrent;
            else
                ViewData["page"] = 1;
            if (sortOrder != "0")
                ViewData["sort"] = sortOrder;
            else
                ViewData["sort"] = "0";
            var data = await _productService.GetAll(sortOrder, pageCurrent);
            ViewData["totalPage"] = data.TotalPages;
            ViewData["products"] = data.items;
            return Page();
        }
    }
}

RAShop.CustomerSite/Pages/Product/SearchProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RAShop.CustomerSite.Interfaces;

namespace RAShop.CustomerSite.Pages.Home
{
    public class SearchProductModel : PageModel
    {
        private readonly IProduct _productService;
        private readonly ICategory _categoryService;
        private readonly ISubCategory _subCategoryService;
        public SearchProductModel(IProduct productService, ICategory categoryService, ISubCategory subCategoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _subCategoryService = subCategoryService;
        }
        public async Task<IActionResult> OnGetAsync(string searchString, string sortOrder = "0", int pageCurrent = 1)
        {
            
            if (pageCurrent > 1)
                ViewData["page"] = pageCurrent;
            else
                ViewData["page"] = 1;
            if (sortOrder != "0")
                ViewData["sort"] = sortOrder;
            else
                ViewData["sort"] = "0";
            searchString = Request.Query["searchString"];
            var data = await _productService.SearchProducts(searchString, sortOrder, pageCurrent);
            ViewData["totalPage"] = data.TotalPages;
            ViewData["searchString"] = searchString;
            ViewData["products"] = data.items;
            return Page();
        }
    }
}

RAShop.CustomerSite/Pages/Product/GetProductByCateId.cshtml
@page 
@using RAShop.CustomerSite.Pages.Home
@model GetProductByCateIdModel
@{
    var pageCurrent = (int)ViewData["page"];
    int totalPages = (int)ViewData["totalPage"];
    int cateId = (int)ViewData["cateId"];
    string sort = (string)ViewData["sort"];
    var products =  ViewData["products"] as List<ProductDTO>;
    @* var nameCate = (string)ViewData["nameCate"]; *@
}
@if(products.Count != null)
{
<div class="container mt-5">
    <div class="row">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-page="/Index">Trang chủ</a></li>
                <li class="breadcrumb-item"><a asp-page="/Product/ProductIndex">Tất cả sản phẩm</a></li>
                @* <li class="breadcrumb-item active">@nameCate</li> *@
            </ol>
        </nav>
                <div class="btn-group float-end" style="width: 15%!important; margin-bottom: 20px;">
        @switch (sort)
        {
            case "price":
              <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown"
                aria-expanded="false">
                        Sắp xếp: Giá tăng dần
                    </button>
                break;
            case "price_desc":
               <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown"
                aria-expanded="false">
                        Sắp xếp: Giá giảm dần
                    </button>
                break;
            case "name":
               <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown"
                aria-expanded="false">
                        Sắp xếp: Tên a-z
                    </button>
                break;
            case "name_desc":
              <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown"
                aria-expanded="false">
                        Sắp xếp: Tên z-a
                    </button>
                break;
            default:
                    <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown"
                aria-expanded="false">
                        Sắp xếp
                    </button>
                break;
        }
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" asp-page="/Product/GetProductByCateId"
                        asp-route-cateid="@cateId" asp-route-sortorder="price"
                        asp-route-pageCurrent="1">Giá tăng dần</a>
                        </li>
                        <li><a class="dropdown-item" asp-page="/Product/GetProductByCateId"
                        asp-route-cateid="@cateId" asp-route-sortorder="price_desc"
                        asp-route-pageCurrent="1">Giá giảm dần</a>
                        </li>
                        <li><a class="dropdown-item" asp-page="/Product/GetProductByCateId"
                        asp-route-cateid="@cateId" asp-route-sortorder="name"
                        asp-route-pageCurrent="1">Tên a-z</a>
                        </li>
                        <li><a class="dropdown-item" asp-page="/Product/GetProductByCateId"
                        asp-route-cateid="@cateId" asp-route-sortorder="name_desc"
                        asp-route-pageCurrent="1">Tên z-a</a>
                        </li>
                    </ul>
                </div>

    </div>
    <div class="d-flex flex-wrap">
        @foreach (var item in products)
        {
            <div class="card-fix">
                <a asp-page="/Product/GetProductDetail" asp-route-id="@item.ProductId">
                    <img title="@item.ProductName" src="@item.MainImg" class="card-img-top" alt="@item.ProductName">
                </a>
                <div class="card-body">
                     @{
                            var name = "";
                            if (item.ProductName.Length < 26)
                            {
                                name = item.ProductName;
                            }
                            else
                            {
                                name = item.ProductName.Substring(0, 25) + "...";
                            }
                        }
                        <h5 class="card-title ms-3 " style="font-size: 18px;">@name</h5>
                    <hr>
                    <p class="card-text text-center fs-5" style="color:#e68b24 ;">@string.Format("{0:#,##0.##}₫",
                    @item.Price)</p>
                    @* <a class="btn btn-addtocart" asp-controller="ShoppingCart" asp-action="AddProdToCart"
                        asp-route-prodid="@item.ProductId">Buy</a> *@
                </div>
            </div>
        }
    </div>
</div>

@if (totalPages == 1)
{

}
else if (pageCurrent == 1)
{
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
            <li class="page-item "><a class="page-link" asp-page="/Product/GetProductByCateId"
                asp-route-cateid="@cateId" asp-route-sortorder="@sort"
                asp-route-pageCurrent="@(pageCurrent + 1)">Sau</a>
            </li>
        </ul>
    </nav>
}
else if (pageCurrent == totalPages)
{
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
            <li class="page-item "><a class="page-link" asp-page="/Product/GetProductByCateId"
                asp-route-cateid="@cateId" asp-route-sortorder="@sort"
                asp-route-pageCurrent="@(pageCurrent - 1)">Trước</a></li>
        </ul>
    </nav>
}
else
{
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
            <li class="page-item "><a class="page-link" asp-page="/Product/GetProductByCateId"
                asp-route-cateid="@cateId" asp-route-pageCurrent="@(pageCurrent - 1)">Trước</a></li>
            <li class="page-item "><a class="page-link" asp-page="/Product/GetProductByCateId"
                asp-route-cateid="@cateId" asp-route-sortorder="@sort"
                asp-route-pageCurrent="@(pageCurrent + 1)">Sau</a></li>
        </ul>
    </nav>
}
}
else
{
    <h3>Not found product</h3>
}

RAShop.CustomerSite/Pages/Product/GetProductDetail.cshtml
@page
@using RAShop.CustomerSite.Pages.Home
@using RAShop.Shared.DTO
@model GetProductDetail
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    var ratingAvgtemp = Convert.ToDouble(ViewData["ratingAvg"]);
    var ratingAvg = string.Format("{0:0.##}%", (Convert.ToDouble(ViewData["ratingAvg"]) / 5) * 100);
    var listRatings = ViewData["listRatings"] as List<RatingDTO>;
    var userName = HttpContextAccessor.HttpContext?.Session.GetString("UserName");
}
<section class="py-4">
    <div class="container px-4 px-lg-5">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-page="/Index">Trang chủ</a></li>
                <li class="breadcrumb-item"><a asp-page="/Product/ProductIndex">Tất cả sản phẩm</a></li>
                @if (Model.product.SubCategoryId != null)
                {
                    <li class="breadcrumb-item"><a asp-page="/Product/GetProductByCateId" asp-route-cateid="@Model.product.CategoryId">@Model.product.CategoryName</a></li>
                    <li class="breadcrumb-item"><a asp-page="/Product/GetProductBySubCateId" asp-route-cateid="@Model.product.SubCategoryId">@Model.product.SubCategoryName</a></li>
                }
                else
                {
                    <li class="breadcrumb-item"><a asp-page="/Product/GetProductByCateId" asp-route-cateid="@Model.product.CategoryId">@Model.product.CategoryName</a></li>
                }


            </ol>
        </nav>
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="@Model.product.MainImg" alt="..." /></div>
            <div class="col-md-6">
                @* <div class="small mb-1 pb-3" style="display: inline-block ;">Loại sản phẩm:
                    @Model.product.CategoryName
                    </div> *@
                <h1 class="display-6 fw-bolder">@Model.product.ProductName</h1>
                <div class="small mb-1" style="display: inline-block ;">Xuất xứ: @Model.product.Origin</div>
                <div class="small mb-1" style="display: inline-block ; float:right;">Đơn vị tính: @Model.product.Unit
                </div>
                <div class="fs-5 mb-1">
                    Giá:
                    <span style="color:#e68b24"> @string.Format("{0:#,##0.##}₫", Model.product.Price)</span>
                </div>
                <div class="star-ratings" style="display: inline-block; font-size: 18px">
                    <div class="fill-ratings" id="star-avg" style="width: @ratingAvg;">
                        <span>★★★★★</span>
                    </div>
                    <div class="empty-ratings">
                        <span>★★★★★</span>
                    </div>
                </div>
                <hr>
                <pre class="commit">
        CAM KẾT KHI MUA SẮM
        - Tư vấn nhiệt tình & tận tâm.
        - Đảm bảo nguồn gốc & chất lượng sản phẩm.
        - Tích lũy điểm, nâng hạng thẻ VIP & tận hưởng ưu đãi đặc quyền.
                        </pre>
                <div class="">
                    <a class="btn-addtocart" asp-page="/Cart/ShoppingCart" asp-page-handler="AddToCart"
                        asp-route-id="@Model.product.ProductId">
                        <div class="glyphicon glyphicon-shopping-cart"></div>
                        Thêm vào giỏ hàng
                    </a>
                    <a class="btn-backtolist" asp-page="/Product/ProductIndex">
                        <div class="glyphicon glyphicon-backward"></div>
                        Quay lại
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<div style="background-color: #F5F5F5; padding-bottom: 20px;">
    <div class="accordion" id="accordionPanelsStayOpenExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                <button class="accordion-button fs-5" type="button" data-bs-toggle="collapse"
                    data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true"
                    aria-controls="panelsStayOpen-collapseOne"
                    style="border-bottom: 3px solid #0c6363; display: inline-block">
                    CHI TIẾT SẢN PHẨM
                </button>
            </h2>
            <div class="container">
                <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show"
                    aria-labelledby="panelsStayOpen-headingOne">
                    <div class="accordion-body" style="white-space: pre-line">
                       @Model.product.Description
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div style="background-color: #F5F5F5; padding-bottom: 20px;">
    <div class="accordion" id="accordionPanelsStayOpenExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                <button class="accordion-button fs-5" type="button" data-bs-toggle="collapse"
                    data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="true"
                    aria-controls="panelsStayOpen-collapseTwo"
                    style="border-bottom: 3px solid #0c6363; display: inline-block">
                    ĐÁNH GIÁ SẢN PHẨM
                </button>
            </h2>
            <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse show"
                aria-labelledby="panelsStayOpen-headingTwo">
                <div class="accordion-body">
                    <div class="row">
                        <div class="col-4">
                            <div class="star-ratings" style="display: inline-block;">
                                <div class="fill-ratings" id="star-avg" style="width: @ratingAvg;">
                                    <span>★★★★★</span>
                                </div>
                                <div class="empty-ratings">
                                    <span>★★★★★</span>
                                </div>
                                <p>@ratingAvg (@listRatings?.Count() đánh giá)</p>
                            </div>
                            <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                                data-bs-target="#staticBackdrop" data-bs-whatever="@@getbootstrap"
                                style="display:block ;">Viết đánh giá</button>
                            @* Start form rating *@

                            <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true"
                                aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Đánh giá:
                                                @Model.product.ProductName</h5>
                                        </div>
                                        <div class="modal-body">
                                            <form asp-page="/Product/GetProductDetail" asp-page-handler="CreateRating"
                                                method="post" onsubmit="">

                                                <div class="star-rating">
                                                    <input type="radio" id="5-stars" name="Star" value="5" checked />
                                                    <label for="5-stars" class="star">&#9733;</label>
                                                    <input type="radio" id="4-stars" name="Star" value="4" />
                                                    <label for="4-stars" class="star">&#9733;</label>
                                                    <input type="radio" id="3-stars" name="Star" value="3" />
                                                    <label for="3-stars" class="star">&#9733;</label>
                                                    <input type="radio" id="2-stars" name="Star" value="2" />
                                                    <label for="2-stars" class="star">&#9733;</label>
                                                    <input type="radio" id="1-star" name="Star" value="1" />
                                                    <label for="1-star" class="star">&#9733;</label>
                                                </div>
                                                <div class="mb-3">
                                                    <textarea class="form-control" name="Comment" id="comment"
                                                        placeholder="Viết nhận xét..." required></textarea>
                                                </div>
                                                <div class="mb-3" hidden>
                                                    <label for="productid" name="Star" class="col-form-label">Số
                                                        sao:</label>
                                                    <input type="text" class="form-control" name="ProductId"
                                                        value="@Model.product.ProductId" id="productid">
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary"
                                                        data-bs-dismiss="modal">Đóng</button>
                                                    <button type="submit" class="btn btn-primary">Đánh giá</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @* End form rating *@
                        </div>
                        <div class="col-8">
                            @{
                                if (ratingAvgtemp == 0)
                                {
                                    <h3>Chưa có đánh giá</h3>
                                }
                                else
                                {
                                    foreach (var rating in listRatings)
                                    {
                                        <div class="row" style="min-height: 100px; margin-bottom: 15px;">
                                            <div>
                                                @{
                                                    var i = 0;
                                                    while (i < rating.Star)
                                                    {
                                                        <i style="color: #FDD836;" class="fas fa-star"></i>
                                                        i++;
                                                    }
                                                }
                                                <p>@rating.DateCreated</p>
                                                <p>@rating.Comment</p>
                                            </div>
                                        </div>
                                    }
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .accordion-button:not(.collapsed) {
        background-color: #fff;
        color: #0c6363;
    }

    .accordion-button:hover {
        border-color: #fff;
        box-shadow: none;
    }

    .accordion-button:focus {
        border-color: #fff;
        box-shadow: none;
    }

    .star-rating {
        display: flex;
        flex-direction: row-reverse;
        font-size: 3.5em;
        justify-content: space-around;
        padding: 0 .2em;
        text-align: center;
        width: 5em;
    }

    .star-rating input {
        display: none;
    }

    .star-rating label {
        color: #ccc;
        cursor: pointer;
    }

    .star-rating :checked~label {
        color: #f90;
    }

    .star-rating label:hover,
    .star-rating label:hover~label {
        color: #fc0;
    }

    .star-ratings {
        unicode-bidi: bidi-override;
        color: #ccc;
        font-size: 64px;
        position: relative;
        margin: 0;
        padding: 0;
    }

    .fill-ratings {
        color: #e7711b;
        padding: 0;
        position: absolute;
        z-index: 1;
        display: block;
        top: 0;
        left: 0;
        overflow: hidden;
    }

    // Allows us to grab the width of the span elements
    span {
        display: inline-block;
    }

    .empty-ratings {
        padding: 0;
        display: block;
        z-index: 0;
    }

    .star-ratings>p {
        font-size: 15px;
    }
</style>